# Generated by Django 5.2.4 on 2026-08-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('OWNER', 'School Owner'), ('PRINCIPAL', 'Principal'), ('VICE_PRINCIPAL', 'Vice Principal'), ('REGISTRAR', 'Registrar'), ('ACCOUNTANT', 'Accountant'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('LIBRARIAN', 'Librarian'), ('IT_ADMIN', 'IT Administrator'), ('DEVELOPER', 'System Developer')], default='STUDENT', max_length=30),
        ),
    ]
