# Generated by Django 5.2.4 on 2026-08-02 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='communications/messages/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-read_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-pinned', '-published_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='document',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='audience',
            field=models.CharField(choices=[('ALL', 'Everyone'), ('STAFF', 'Staff'), ('TEACHERS', 'Teachers'), ('STUDENTS', 'Students'), ('PARENTS', 'Parents'), ('ADMINISTRATION', 'Administration')], default='ALL', max_length=30),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='allow_email',
            field=models.BooleanField(default=False, help_text='Reserved for future email integration.'),
        ),
        migrations.AddField(
            model_name='notice',
            name='allow_sms',
            field=models.BooleanField(default=False, help_text='Reserved for future SMS integration.'),
        ),
        migrations.AddField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='communications/notices/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_communication_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notice',
            name='audience',
            field=models.CharField(choices=[('ALL', 'Everyone'), ('STAFF', 'All Staff'), ('TEACHERS', 'Teachers'), ('STUDENTS', 'Students'), ('PARENTS', 'Parents'), ('REGISTRAR', 'Registrar'), ('FINANCE', 'Finance Staff'), ('PRINCIPAL', 'Principal and Administration')], default='ALL', max_length=30),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notice',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['status'], name='communicati_status_51b111_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['audience'], name='communicati_audienc_9e49dd_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['priority'], name='communicati_priorit_3eb6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['publish_at'], name='communicati_publish_295785_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['expires_at'], name='communicati_expires_87daa9_idx'),
        ),
        migrations.AddField(
            model_name='internalmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_internal_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagerecipient',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_records', to='communications.internalmessage'),
        ),
        migrations.AddField(
            model_name='messagerecipient',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recipient_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalmessage',
            name='recipients',
            field=models.ManyToManyField(related_name='received_internal_messages', through='communications.MessageRecipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticeread',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='communications.notice'),
        ),
        migrations.AddField(
            model_name='noticeread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_read_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='messagerecipient',
            constraint=models.UniqueConstraint(fields=('message', 'recipient'), name='unique_message_recipient'),
        ),
        migrations.AddConstraint(
            model_name='noticeread',
            constraint=models.UniqueConstraint(fields=('notice', 'user'), name='unique_notice_read_user'),
        ),
    ]
