# Generated by Django 5.2.4 on 2026-08-01 10:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_gradelevel_active_gradelevel_grading_system'),
        ('examinations', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('FIRST_PERIOD', '1st Period'), ('SECOND_PERIOD', '2nd Period'), ('THIRD_PERIOD', '3rd Period'), ('FIRST_SEMESTER_EXAM', '1st Semester Exam'), ('FOURTH_PERIOD', '4th Period'), ('FIFTH_PERIOD', '5th Period'), ('SIXTH_PERIOD', '6th Period'), ('SECOND_SEMESTER_EXAM', '2nd Semester Exam')], max_length=40)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('score_entry_open', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['academic_year__start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('class_activity_score', models.DecimalField(decimal_places=2, default=0, help_text='Attendance and participation score.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('quiz_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('period_test_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('semester_exam_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['enrollment__student__last_name', 'subject__name', 'period__order'],
            },
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='gradescale',
            options={'ordering': ['grading_system', '-min_score']},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assessment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='grading_system',
            field=models.CharField(choices=[('NUMERIC', 'Numeric Grading'), ('LETTER', 'Letter Grading (A–F)')], default='NUMERIC', max_length=20),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.classsection'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.term'),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='max_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='min_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='remark',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('assessment', 'student'), name='unique_assessment_student_score'),
        ),
        migrations.AddField(
            model_name='resultperiod',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_periods', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_subject_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='academics.enrollment'),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_subject_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_results', to='examinations.resultperiod'),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_results', to='academics.subject'),
        ),
        migrations.AddConstraint(
            model_name='resultperiod',
            constraint=models.UniqueConstraint(fields=('academic_year', 'code'), name='unique_result_period_per_year'),
        ),
        migrations.AddIndex(
            model_name='subjectresult',
            index=models.Index(fields=['period', 'subject'], name='examination_period__a4dd5a_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectresult',
            index=models.Index(fields=['approved', 'published'], name='examination_approve_22cc4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='subjectresult',
            constraint=models.UniqueConstraint(fields=('enrollment', 'subject', 'period'), name='unique_student_subject_period_result'),
        ),
    ]
