# Generated by Django 5.2.4 on 2026-08-02 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0007_alter_enrollment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Annie T. Doe Memorial Foundation High School', max_length=255)),
                ('short_name', models.CharField(default='ATDMF-SMIS', max_length=100)),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('principal_name', models.CharField(blank=True, max_length=150)),
                ('registrar_name', models.CharField(blank=True, max_length=150)),
                ('default_currency', models.CharField(choices=[('LRD', 'Liberian Dollar'), ('USD', 'United States Dollar'), ('BOTH', 'LRD and USD')], default='BOTH', max_length=10)),
                ('bank_name', models.CharField(blank=True, default='LBDI Bank', max_length=150)),
                ('bank_account_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number_lrd', models.CharField(blank=True, max_length=100)),
                ('bank_account_number_usd', models.CharField(blank=True, max_length=100)),
                ('receipt_footer', models.TextField(blank=True)),
                ('report_footer', models.TextField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_online_registration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_settings_records', to='academics.academicyear')),
                ('active_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_settings_records', to='academics.term')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_school_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
    ]
