# Generated by Django 5.2.4 on 2026-08-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='school_name',
            field=models.CharField(default='Annie T. Doe Memorial Academy', max_length=255),
        ),
    ]
