# Generated by Django 5.2.4 on 2026-08-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0002_alter_schoolsettings_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='certificate_address',
            field=models.CharField(blank=True, default='Lower Buchanan, Grand Bassa County, Liberia', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='certificate_footer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='certificate_intro_text',
            field=models.CharField(blank=True, default='This certificate is proudly presented to', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='certificate_school_name',
            field=models.CharField(blank=True, default='Annie T. Doe Memorial Academy', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='certificate_show_principal_signature',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='certificate_show_registrar_signature',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='id_card_address',
            field=models.CharField(blank=True, default='Lower Buchanan, Grand Bassa County, Liberia', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='id_card_footer',
            field=models.CharField(blank=True, default='This card remains the property of Annie T. Doe Memorial Academy.', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='id_card_show_signature',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='id_card_title',
            field=models.CharField(default='OFFICIAL IDENTIFICATION CARD', max_length=150),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='principal_signature',
            field=models.ImageField(blank=True, null=True, upload_to='school/signatures/'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='principal_title',
            field=models.CharField(blank=True, default='Principal', max_length=120),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='registrar_signature',
            field=models.ImageField(blank=True, null=True, upload_to='school/signatures/'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='registrar_title',
            field=models.CharField(blank=True, default='Registrar', max_length=120),
        ),
    ]
