# Generated by Django 5.2.4 on 2026-07-30 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffmember'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.classsection'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.gradelevel'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classsection'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffmember'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classsection'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffmember'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='classsection',
            unique_together={('grade', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together={('subject', 'class_section', 'academic_year')},
        ),
    ]
