# Generated by Django 5.2.4 on 2026-08-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_enrollment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradelevel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='grading_system',
            field=models.CharField(choices=[('NUMERIC', 'Numeric Grading'), ('LETTER', 'Letter Grading (A–F)')], default='NUMERIC', help_text='Use Letter Grading for ECD/K-1 and Numeric Grading for other grade levels.', max_length=20),
        ),
    ]
