# Generated by Django 5.2.4 on 2026-08-01 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_gradelevel_active_gradelevel_grading_system'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('PROMOTED', 'Promoted'), ('REPEATED', 'Repeated'), ('GRADUATED', 'Graduated'), ('WITHDRAWN', 'Withdrawn')], default='PROMOTED', max_length=20)),
                ('yearly_average', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_promotions', to=settings.AUTH_USER_MODEL)),
                ('source_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_promotions', to='academics.academicyear')),
                ('source_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_promotions', to='academics.classsection')),
                ('source_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_records', to='academics.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_records', to='students.student')),
                ('target_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_promotions', to='academics.academicyear')),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_promotions', to='academics.classsection')),
                ('target_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_promotion', to='academics.enrollment')),
            ],
            options={
                'ordering': ['-processed_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'source_academic_year', 'target_academic_year'), name='unique_student_year_promotion')],
            },
        ),
    ]
