# Generated by Django 5.2.4 on 2026-08-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_studentpromotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
    ]
