# Generated by Django 5.2.4 on 2026-08-02 10:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_bankaccount_expensecategory_sponsor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_number', models.CharField(blank=True, max_length=100)),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('statement_file', models.FileField(upload_to='finance/bank_statements/%Y/%m/')),
                ('file_type', models.CharField(blank=True, help_text='PDF, XLSX, XLS, or CSV', max_length=20)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('REVIEW_REQUIRED', 'Review Required'), ('RECONCILED', 'Fully Reconciled'), ('FAILED', 'Import Failed')], default='UPLOADED', max_length=30)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('matched_transactions', models.PositiveIntegerField(default=0)),
                ('unmatched_transactions', models.PositiveIntegerField(default=0)),
                ('duplicate_transactions', models.PositiveIntegerField(default=0)),
                ('total_statement_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-week_end_date', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('bank_slip_number', models.CharField(blank=True, max_length=100)),
                ('bank_reference', models.CharField(blank=True, max_length=150)),
                ('depositor_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='LRD', max_length=10)),
                ('match_status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched'), ('DUPLICATE', 'Duplicate'), ('IGNORED', 'Ignored'), ('MANUAL_REVIEW', 'Manual Review')], default='UNMATCHED', max_length=30)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['transaction_date', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at']},
        ),
        migrations.RemoveField(
            model_name='bankdeposit',
            name='bank_slip_image',
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_slip_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_school_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_reprint_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='statement_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='statement_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_against_statement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.studentinvoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('BANK_DEPOSIT', 'LBDI Bank Deposit'), ('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='BANK_DEPOSIT', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_school_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['receipt_number'], name='finance_pay_receipt_578993_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bank_slip_number'], name='finance_pay_bank_sl_02aa68_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at'], name='finance_pay_paid_at_ef8be0_idx'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_statements', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_bank_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_bank_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankstatementtransaction',
            name='matched_bank_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_transactions', to='finance.bankdeposit'),
        ),
        migrations.AddField(
            model_name='bankstatementtransaction',
            name='matched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_statement_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankstatementtransaction',
            name='matched_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_transactions', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='bankstatementtransaction',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.bankstatement'),
        ),
        migrations.AddConstraint(
            model_name='bankstatement',
            constraint=models.UniqueConstraint(fields=('bank_account', 'week_start_date', 'week_end_date'), name='unique_weekly_bank_statement'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['bank_slip_number'], name='finance_ban_bank_sl_69d4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['bank_reference'], name='finance_ban_bank_re_3b67b3_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['match_status'], name='finance_ban_match_s_188c3e_idx'),
        ),
    ]
