# Generated by Django 5.2.4 on 2026-08-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_bankstatement_bankstatementtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('LRD', 'Liberian Dollar'), ('USD', 'United States Dollar')], default='LRD', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('LRD', 'Liberian Dollar'), ('USD', 'United States Dollar')], default='LRD', max_length=3),
        ),
    ]
