# Generated by Django 5.2.4 on 2026-08-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expense_currency_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinvoice',
            name='currency',
            field=models.CharField(choices=[('LRD', 'Liberian Dollar'), ('USD', 'United States Dollar')], default='LRD', max_length=3),
        ),
    ]
