# Generated by Django 5.2.4 on 2026-08-02 12:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_enrollment_options_and_more'),
        ('attendance', '0001_initial'),
        ('employees', '0001_initial'),
        ('students', '0002_guardian_active_guardian_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused'), ('S', 'Sick'), ('LV', 'On Leave')], default='P', max_length=2)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('corrected', models.BooleanField(default=False)),
                ('correction_reason', models.TextField(blank=True)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'employee__last_name', 'employee__first_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='studentattendance',
            options={'ordering': ['-date', 'student__last_name', 'student__first_name']},
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='corrected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_student_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='correction_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_attendance_records', to='academics.classsection'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_student_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused'), ('S', 'Sick')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_attendance_records', to='academics.term'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['date'], name='attendance__date_12ec13_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['status'], name='attendance__status_938ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['class_section', 'date'], name='attendance__class_s_ddc424_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['term', 'date'], name='attendance__term_id_c8830d_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_student_attendance_date'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_employee_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_employee_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['date'], name='attendance__date_f21864_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['status'], name='attendance__status_06387a_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_attendance_date'),
        ),
    ]
