# Generated by Django 5.2.4 on 2026-08-07 09:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_employeeattendance_alter_studentattendance_options_and_more'),
        ('students', '0002_guardian_active_guardian_created_at_and_more'),
        ('teacher_assignments', '0002_schoolperiod_timetableentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_attendance_sessions', to=settings.AUTH_USER_MODEL)),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='teacher_assignments.teacherassignment')),
                ('timetable_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='teacher_assignments.timetableentry')),
            ],
            options={
                'ordering': ['-date', 'teacher_assignment__class_section'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused'), ('S', 'Sick'), ('SU', 'Under Suspension')], default='P', max_length=2)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_attendance_records', to='students.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.classroomattendancesession')),
            ],
            options={
                'ordering': ['student__last_name', 'student__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='classroomattendancesession',
            index=models.Index(fields=['date'], name='attendance__date_69344b_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomattendancesession',
            index=models.Index(fields=['submitted'], name='attendance__submitt_dc9a0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomattendancesession',
            constraint=models.UniqueConstraint(fields=('teacher_assignment', 'timetable_entry', 'date'), name='unique_classroom_attendance_session'),
        ),
        migrations.AddIndex(
            model_name='classroomattendancerecord',
            index=models.Index(fields=['status'], name='attendance__status_0578ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomattendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_student_classroom_attendance'),
        ),
    ]
