# Generated by Django 5.2.4 on 2026-08-01 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_alter_enrollment_created_at_and_more'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_periods', models.PositiveSmallIntegerField(default=3, help_text='Number of periods taught each week.')),
                ('is_class_teacher', models.BooleanField(default=False, help_text='Select when this employee is the class teacher.')),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='academics.academicyear')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='academics.classsection')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'active': True, 'is_teacher': True}, on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='employees.employee')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='academics.term')),
            ],
            options={
                'ordering': ['academic_year__name', 'term__name', 'class_section__grade__order', 'class_section__name', 'subject__name'],
                'indexes': [models.Index(fields=['academic_year', 'term'], name='teacher_ass_academi_385acd_idx'), models.Index(fields=['teacher', 'active'], name='teacher_ass_teacher_8aae71_idx'), models.Index(fields=['class_section', 'active'], name='teacher_ass_class_s_576949_idx')],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'term', 'class_section', 'subject'), name='unique_subject_teacher_per_class_term')],
            },
        ),
    ]
