# Generated by Django 5.2.4 on 2026-08-07 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Period 1, Period 2, Lunch Break', max_length=100)),
                ('period_number', models.PositiveSmallIntegerField(unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_teaching_period', models.BooleanField(default=True, help_text='Disable for lunch, devotion, assembly or other non-teaching periods.')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['period_number'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('room', models.CharField(blank=True, help_text='Optional classroom, laboratory or room.', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='teacher_assignments.schoolperiod')),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='teacher_assignments.teacherassignment')),
            ],
            options={
                'ordering': ['day', 'period__period_number'],
                'indexes': [models.Index(fields=['day', 'active'], name='teacher_ass_day_a4e329_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher_assignment', 'day', 'period'), name='unique_assignment_day_period')],
            },
        ),
    ]
