import { useEffect, useMemo, useRef, useState } from "react";
import { Print } from "@mui/icons-material";
import { Box, Button, FormControl, InputLabel, MenuItem, Paper, Select, Stack, Typography } from "@mui/material";
import JsBarcode from "jsbarcode";
import QRCode from "qrcode";
import api from "../api/client";
const list=r=>Array.isArray(r.data)?r.data:r.data.results||[];
function Barcode({value}){const ref=useRef();useEffect(()=>{if(value)JsBarcode(ref.current,value,{format:"CODE128",height:34,fontSize:10,margin:0})},[value]);return <svg ref={ref}/>}
function QR({value}){const [src,setSrc]=useState("");useEffect(()=>{if(value)QRCode.toDataURL(value,{width:130,margin:1}).then(setSrc)},[value]);return src?<img src={src} alt="QR code" style={{width:90,height:90}}/>:null}
export default function IDCards(){const[type,setType]=useState("STUDENT"),[records,setRecords]=useState([]),[id,setId]=useState("");useEffect(()=>{api.get(type==="STUDENT"?"/students/records/":"/employees/employees/",{params:{page_size:2000}}).then(r=>setRecords(list(r)));setId("")},[type]);const p=useMemo(()=>records.find(x=>String(x.id)===String(id)),[records,id]);const code=type==="STUDENT"?p?.admission_number:p?.employee_id;const photo=p?.photo_url||p?.photo;return <Box><style>{`@media print{body *{visibility:hidden!important}#print-card,#print-card *{visibility:visible!important}#print-card{position:absolute;left:0;top:0}}`}</style><Typography variant="h4" fontWeight={900} color="#0B2A78">ID Card Generator</Typography><Typography color="text.secondary" mb={3}>CR80 student and staff cards with Code 128 barcode and QR code.</Typography><Paper sx={{p:3,borderRadius:3,mb:3}}><Stack direction={{xs:"column",md:"row"}} spacing={2}><FormControl fullWidth><InputLabel>Card Type</InputLabel><Select label="Card Type" value={type} onChange={e=>setType(e.target.value)}><MenuItem value="STUDENT">Student</MenuItem><MenuItem value="EMPLOYEE">Staff</MenuItem></Select></FormControl><FormControl fullWidth><InputLabel>Select Person</InputLabel><Select label="Select Person" value={id} onChange={e=>setId(e.target.value)}>{records.map(x=><MenuItem key={x.id} value={x.id}>{x.full_name} — {x.admission_number||x.employee_id}</MenuItem>)}</Select></FormControl><Button variant="contained" startIcon={<Print/>} disabled={!p} onClick={()=>window.print()}>Print</Button></Stack></Paper>{p&&<Stack id="print-card" direction={{xs:"column",lg:"row"}} spacing={3} sx={{width:"max-content",mx:"auto"}}><Card front p={p} code={code} type={type} photo={photo}/><Card p={p} code={code} type={type}/></Stack>}</Box>}
function Card({front,p,code,type,photo}){return <Paper sx={{width:"85.6mm",height:"53.98mm",borderRadius:"3mm",overflow:"hidden",position:"relative",p:0}}>{front?<><Box sx={{bgcolor:"#071B54",color:"white",p:"3mm",display:"flex",alignItems:"center",gap:"2mm"}}><img src="/atdmf-seal.jpeg" style={{width:"10mm",height:"10mm",borderRadius:"50%"}}/><Box><Typography sx={{fontSize:"3.5mm",fontWeight:900}}>ANNIE T. DOE MEMORIAL ACADEMY</Typography><Typography sx={{fontSize:"2mm"}}>Lower Buchanan, Grand Bassa County, Liberia</Typography></Box></Box><Box sx={{p:"3mm",display:"grid",gridTemplateColumns:"25mm 1fr",gap:"3mm"}}><Box component="img" src={photo||"/atdmf-seal.jpeg"} sx={{width:"24mm",height:"29mm",objectFit:"cover",border:"1px solid #C8102E"}}/><Box><Typography sx={{fontSize:"2mm",color:"#64748B"}}>FULL NAME</Typography><Typography sx={{fontSize:"4mm",fontWeight:900,color:"#071B54"}}>{p.full_name}</Typography><Typography sx={{fontSize:"2mm",color:"#64748B",mt:1}}>ID NUMBER</Typography><Typography sx={{fontSize:"3.3mm",fontWeight:800}}>{code}</Typography><Typography sx={{fontSize:"2.5mm",fontWeight:800,mt:1}}>{type==="STUDENT"?"STUDENT":"STAFF"}</Typography></Box></Box></>:<Stack alignItems="center" justifyContent="space-between" sx={{height:"100%",p:"4mm"}}><Typography fontWeight={900} color="#071B54">OFFICIAL IDENTIFICATION CARD</Typography><Stack direction="row" alignItems="center" spacing={2}><Barcode value={code}/><QR value={code}/></Stack><Typography sx={{fontSize:"2.2mm",textAlign:"center"}}>This card remains the property of Annie T. Doe Memorial Academy.</Typography></Stack>}</Paper>}
