# Generated by Django 5.2.4 on 2026-08-03 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_enrollment_options_and_more'),
        ('import_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='academics.academicyear'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='import_type',
            field=models.CharField(choices=[('SPONSORSHIP', 'Students, Guardians and Sponsorships'), ('EMPLOYEE', 'Employees / Staff')], max_length=30),
        ),
    ]
